# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rex < Formula
  desc "Zero-config universal project runner"
  homepage "https://rexrun.dev"
  version "0.4.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rexrun-dev/rex/releases/download/v0.4.0/rex_0.4.0_darwin_amd64.tar.gz"
      sha256 "4a3e2ad8753b84c9a16b8a0738afca491188db29c0e2f5ecd162efe301a70577"

      define_method(:install) do
        bin.install "rex"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rexrun-dev/rex/releases/download/v0.4.0/rex_0.4.0_darwin_arm64.tar.gz"
      sha256 "46af6bd0df2921a39ad277240e72babeb0255377b3f4e0859e7744ef4464ae91"

      define_method(:install) do
        bin.install "rex"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rexrun-dev/rex/releases/download/v0.4.0/rex_0.4.0_linux_amd64.tar.gz"
      sha256 "86e7f861144c7458611eb5ce143ad3886b34ca0b69e41373cd61ec513eeb197b"
      define_method(:install) do
        bin.install "rex"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rexrun-dev/rex/releases/download/v0.4.0/rex_0.4.0_linux_arm64.tar.gz"
      sha256 "b2bf0e2d9f399a1346396fe8a0455b3eb86091f5566e373ebb511ab9e08a18de"
      define_method(:install) do
        bin.install "rex"
      end
    end
  end

  test do
    assert_match "rex", shell_output("#{bin}/rex -v")
  end
end
