# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rex < Formula
  desc "Zero-config universal project runner"
  homepage "https://rexrun.dev"
  version "0.5.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rexrun-dev/rex/releases/download/v0.5.0/rex_0.5.0_darwin_amd64.tar.gz"
      sha256 "6526571963d5e93d34264877b748265b16b3187133cb74aba4d1beaede4c8ec5"

      define_method(:install) do
        bin.install "rex"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rexrun-dev/rex/releases/download/v0.5.0/rex_0.5.0_darwin_arm64.tar.gz"
      sha256 "27dc0f5d3e9ee341217a5bb9015d673cf5d7a2aa2a2f6ff70f44f61636293495"

      define_method(:install) do
        bin.install "rex"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rexrun-dev/rex/releases/download/v0.5.0/rex_0.5.0_linux_amd64.tar.gz"
      sha256 "d4408ede49273ffcf0b8a0bc99c1a7207e07fbc33e057d60e56d690432fd45ee"
      define_method(:install) do
        bin.install "rex"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rexrun-dev/rex/releases/download/v0.5.0/rex_0.5.0_linux_arm64.tar.gz"
      sha256 "e36b66356c67822405fce3ddbe51465655f5a8811160b12ea8d111e8b5b762a7"
      define_method(:install) do
        bin.install "rex"
      end
    end
  end

  test do
    assert_match "rex", shell_output("#{bin}/rex -v")
  end
end
